config/routes.rb
CdpOpenmrsConnector::Application.routes.draw do
  resources :patient_samples

  root :to => 'patient_samples#new'
  match 'openmrs/patients' => 'open_mrs_api#search_patients'
  match 'openmrs/encounters' => 'open_mrs_api#search_encounters'
  match 'openmrs/result' => 'open_mrs_api#register_result'

end

app/models/open_mrs_api.rb
require 'net/http'

class OpenMrsApi

  def search_patients name
    uri = URI.parse("#{Settings.openmrs_base_url}/patient?q=#{name}")

    req = Net::HTTP::Get.new(uri.request_uri)
    req.basic_auth 'admin', 'Admin123'

    req["Content-Type"] = "application/json"

    res = Net::HTTP.start(uri.hostname, uri.port) {|http|
      http.request(req)
    }

    res.body
  end

  def search_encounters patient_uuid
    uri = URI.parse("#{Settings.openmrs_base_url}/encounter/?patient=#{patient_uuid}")

    req = Net::HTTP::Get.new(uri.request_uri)
    req.basic_auth 'admin', 'Admin123'

    req["Content-Type"] = "application/json"

    res = Net::HTTP.start(uri.hostname, uri.port) {|http|
      http.request(req)
    }

    res.body
  end

  def report_sample patient_sample
    uri = URI.parse("#{Settings.openmrs_base_url}/obs/")

    req = Net::HTTP::Post.new(uri.request_uri)
    req.basic_auth 'admin', 'Admin123'
    req.body = {
      person: patient_sample.patient_uuid,
      obsDatetime: DateTime.now,
      concept: Settings.sample_id_concept_uuid,
      encounter: patient_sample.encounter_uuid,
      value: patient_sample.sample_id
    }.to_json

    req["Content-Type"] = "application/json"

    res = Net::HTTP.start(uri.hostname, uri.port) {|http|
      http.request(req)
    }

    res.body
  end

  def register_result patient_sample, result
    uri = URI.parse("#{Settings.openmrs_base_url}/obs/")

    req = Net::HTTP::Post.new(uri.request_uri)
    req.basic_auth 'admin', 'Admin123'
    req.body = {
      person: patient_sample.patient_uuid,
      obsDatetime: DateTime.now,
      concept: Settings.sample_result_concept_uuid,
      encounter: patient_sample.encounter_uuid,
      value: "#{patient_sample.sample_id} :: #{result}"
    }.to_json

    req["Content-Type"] = "application/json"

    res = Net::HTTP.start(uri.hostname, uri.port) {|http|
      http.request(req)
    }

    res.body
  end
end

app/models/patient_sample.rb
class PatientSample < ActiveRecord::Base
  attr_accessible :patient_uuid, :sample_id, :encounter_uuid, :patient_name, :encounter_name
  validates_presence_of :patient_uuid, :sample_id, :encounter_uuid, :patient_name, :encounter_name
  validates_uniqueness_of :sample_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/open_mrs_api_controller.rb
class OpenMrsApiController < ApplicationController
  def initialize
    @api = OpenMrsApi.new
  end

  def search_patients
    patient_name = params[:name]

    render json: @api.search_patients(patient_name)
  end

  def search_encounters
    patient_uuid = params[:patient]

    render json: @api.search_encounters(patient_uuid)
  end

  def register_result
    sample_id = params[:sample_id]
    result = params[:result]

    Rails.logger.info("Registering result #{result} for sample #{sample_id}")
    patient_sample = PatientSample.where(sample_id: sample_id).first

    if patient_sample
      render json: @api.register_result(patient_sample, result)
    else
      Rails.logger.warn("Sample #{sample_id} not found")
      render json: {success: false, error: "Unknown Sample ID: #{sample_id}"}
    end
  end
end

app/controllers/patient_samples_controller.rb
class PatientSamplesController < ApplicationController

  layout 'application'

  def initialize
    super
    @openmrs_api = OpenMrsApi.new
  end

  # GET /patient_samples
  # GET /patient_samples.json
  def index
    @patient_samples = PatientSample.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @patient_samples }
    end
  end

  # GET /patient_samples/1
  # GET /patient_samples/1.json
  def show
    @patient_sample = PatientSample.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @patient_sample }
    end
  end

  # GET /patient_samples/new
  # GET /patient_samples/new.json
  def new
    @patient_sample = PatientSample.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @patient_sample }
    end
  end

  # GET /patient_samples/1/edit
  def edit
    @patient_sample = PatientSample.find(params[:id])
  end

  # POST /patient_samples
  # POST /patient_samples.json
  def create
    @patient_sample = PatientSample.new(params[:patient_sample])

    respond_to do |format|
      if @patient_sample.save
        report_patient_sample @patient_sample
        format.html { redirect_to @patient_sample, notice: 'Sample was successfully registered' }
        format.json { render json: @patient_sample, status: :created, location: @patient_sample }
      else
        format.html { render action: "new" }
        format.json { render json: @patient_sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /patient_samples/1
  # PUT /patient_samples/1.json
  def update
    @patient_sample = PatientSample.find(params[:id])

    respond_to do |format|
      if @patient_sample.update_attributes(params[:patient_sample])
        format.html { redirect_to @patient_sample, notice: 'Patient sample was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @patient_sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patient_samples/1
  # DELETE /patient_samples/1.json
  def destroy
    @patient_sample = PatientSample.find(params[:id])
    @patient_sample.destroy

    respond_to do |format|
      format.html { redirect_to patient_samples_url }
      format.json { head :no_content }
    end
  end

  def report_patient_sample patient_sample
    response = @openmrs_api.report_sample patient_sample
    JSON.parse(response)['uuid']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/open_mrs_api_helper.rb
module OpenMrsApiHelper
end

app/helpers/patient_samples_helper.rb
module PatientSamplesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CDX OpenMRS Connector</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag "//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css", :media => :all %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>
<body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">CDX OpenMRS Connector</a>
      </div>
    </div>
  </nav>


  <div class="container">

    <div class="template">
      <%= yield %>
    </div>

  </div>






</body>
</html>

app/views/patient_samples/_form.html.erb
<script type="text/javascript">
  function searchPatient() {
    var patientName = document.getElementById("patientName").value

    var httpRequest;
    if (window.XMLHttpRequest) {
        httpRequest = new XMLHttpRequest();
    } else if (window.ActiveXObject) {
        httpRequest = new ActiveXObject("Microsoft.XMLHTTP");
    }
    httpRequest.onreadystatechange = function() {
      if (httpRequest.readyState === 4) {
        if (httpRequest.status === 200) {
          showPatients(JSON.parse(httpRequest.responseText));
        } else {
          console.log('There was a problem with the request.');
        }
      }
    }

    httpRequest.open('GET', '/openmrs/patients?name=' + patientName, true);
    httpRequest.send(null);

  }

  function selectEncounter(event) {
    var selection = event.target;
    var selectedEncounterUuid = selection.getAttribute('data-uuid');

    document.getElementById("patient_sample_encounter_name").value = selection.textContent;
    document.getElementById("patient_sample_encounter_uuid").value = selectedEncounterUuid;
  }

  function selectPatient(event) {
    var selection = event.target;

    var selectedPatientUuid = selection.getAttribute('data-uuid');

    document.getElementById("patient_sample_patient_name").value = selection.textContent;
    document.getElementById("patient_sample_patient_uuid").value = selectedPatientUuid;


    var httpRequest;
    if (window.XMLHttpRequest) {
        httpRequest = new XMLHttpRequest();
    } else if (window.ActiveXObject) {
        httpRequest = new ActiveXObject("Microsoft.XMLHTTP");
    }
    httpRequest.onreadystatechange = function() {
      if (httpRequest.readyState === 4) {
        if (httpRequest.status === 200) {
          showEncounters(JSON.parse(httpRequest.responseText));
        } else {
          console.log('There was a problem with the request.');
        }
      }
    }

    httpRequest.open('GET', '/openmrs/encounters?patient=' + selectedPatientUuid, true);
    httpRequest.send(null);
  }

  function showEncounters(response) {
    var encountersList = document.getElementById('encountersList');
    while(encountersList.firstChild) {
      encountersList.removeChild(encountersList.firstChild);
    }

    for(index in response.results) {
      var result = response.results[index];
      var li = document.createElement('li');
      li.onclick = selectEncounter;
      li.textContent = result.display;
      li.setAttribute("data-uuid", result.uuid);
      encountersList.appendChild(li);
    }
  }

  function showPatients(response) {
    var patientsList = document.getElementById('patientsList');
    while(patientsList.firstChild) {
      patientsList.removeChild(patientsList.firstChild);
    }

    for(index in response.results) {
      var result = response.results[index];
      var li = document.createElement('li');
      li.onclick = selectPatient;
      li.textContent = result.display;
      li.setAttribute("data-uuid", result.uuid);
      patientsList.appendChild(li);
    }
  }
</script>

<%= form_for(@patient_sample) do |f| %>
  <% if @patient_sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient_sample.errors.count, "error") %> prohibited this Sample from being registered:</h2>

      <ul>
      <% @patient_sample.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>Patient name</label>
    <div class="input-group">
      <input type="text" class="form-control" id="patientName" />
      <span class="input-group-btn">
        <input type="button" class="btn btn-default" onclick="javascript:searchPatient();return" value="Search" />
      </span>
    </div>
  </div>

  <ul id="patientsList">
  </ul>

  <div class="form-group">
    <label>Patient</label>
    <%= f.text_field :patient_name, readonly: true, class: 'form-control' %>
    <%= f.hidden_field :patient_uuid %>
  </div>

  <ul id="encountersList">
  </ul>

  <div class="form-group">
    <label>Encounter</label>
    <%= f.text_field :encounter_name, readonly: true, class: 'form-control' %>
    <%= f.hidden_field :encounter_uuid %>
  </div>

  <div class="form-group">
    <label>Sample ID</label>
    <%= f.text_field :sample_id, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/patient_samples/edit.html.erb
<h1>Editing patient_sample</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient_sample %> |
<%= link_to 'Back', patient_samples_path %>

app/views/patient_samples/index.html.erb
<h1>Registered Samples</h1>
<br/>
<table class="table">
  <tr>
    <th>Patient</th>
    <th>Encounter</th>
    <th>Sample ID</th>
  </tr>

<% @patient_samples.each do |patient_sample| %>
  <tr>
    <td><%= patient_sample.patient_name %></td>
    <td><%= patient_sample.encounter_name %></td>
    <td><%= patient_sample.sample_id %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Register new sample', new_patient_sample_path %>

app/views/patient_samples/new.html.erb
<h1>Register the Sample</h1>

<%= render 'form' %>

<%= link_to 'Show all registered samples', patient_samples_path %>

app/views/patient_samples/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Show all registered samples', patient_samples_path %>